### ISSUE TITLE
mkbootimg.osx not working

### ISSUE THREAD

**Issue by gordon0001** [bgcngm/mtk-tools#10]
Binary is not executable under Yosemite 10.10.1

zsh: exec format error: ./mkbootimg.osx

bash: ./mkbootimg.osx: cannot execute binary file

**Comment by bgcngm** [comment]
@carliv, could you help on this?

@gordon0001, could you provide a direct contact like e-mail?

**Comment by carliv** [comment]
Unfortunately I was expecting that... Because it's not compiled in OSX, it doesn't have the right structure of a osx executable file. If @gordon0001 want's to help I can provide the zip with all required files to compile it under OSX and all terminal commands for this. Only it needs to be an OSX with gcc building environment.

**Comment by bgcngm** [comment]
Yes, I think that either @gordon0001 or @stephenbalaban can help us on that.

**Comment by carliv** [comment]
I'm waiting for any of them to contact me to provide all necessary infos.

**Comment by bgcngm** [comment]
Thanks for helping. I can't compile either because I don't have easy access to an OSX machine.

**Comment by gordon0001** [comment]
Hello, sorry for late answer. 
No problem for me to compile this. Contact me at supergordon@drei.at

**Comment by carliv** [comment]
Ok, thanks to @gordon0001 now the problem's solved.
Bruno here it is the compiled module: http://www.datafilehost.com/d/89ad4c68
gordon0001 says he tested it already and it's working fine now (he unpacked, repacked and flashed the image in the phone).

**Comment by bgcngm** [comment]
Thank you both. I'll update the repo as soon as I have time.

**Comment by gordon0001** [comment]
No problem :)
