### ISSUE TITLE
bug compilation in ubuntu 14.04

### ISSUE THREAD

**Issue by Dw0rd** [bgcngm/mtk-tools#13]
Hello.

root@dw0rd-virtual-machine:~/Desktop/andr-kernl# ./mkbootimg 
bash: ./mkbootimg: cannot execute binary file: Exec format error

full compilation log:

root@dw0rd-virtual-machine:~/Desktop/andr-kernl# ./repack-MTK.pl -boot ./boot.img-kernel.img ./boot.img-ramdisk ./my-boot.img
MTK-Tools by Bruno Martins
MTK repack script (last update: 06-01-2015)

Repacking boot image...
Ramdisk size: 3215 blocks

Build information:

 Base address and offsets:

  Base address:         0x10000000
  Kernel offset:        0x00008000
  Ramdisk offset:       0x01000000
  Second stage offset:      0x00f00000
  Tags offset:          0x00000100

 Other:

  Page size (bytes):        2048
  ASCIIZ product name:      '1414054265'
  Command line:         ''
/home/dw0rd/Desktop/andr-kernl/mkbootimg: 1: /home/dw0rd/Desktop/andr-kernl/mkbootimg: ELF: not found
/home/dw0rd/Desktop/andr-kernl/mkbootimg: 2: /home/dw0rd/Desktop/andr-kernl/mkbootimg: Syntax error: "(" unexpected
root@dw0rd-virtual-machine:~/Desktop/andr-kernl#

**Comment by bgcngm** [comment]
Make sure you run the scripts on a 64bit environment.
