### ISSUE TITLE
after repack phone not start

### ISSUE THREAD

**Issue by Dw0rd** [bgcngm/mtk-tools#14]
Hello.

I repack my boot (phone fly iq4516 Octa based on mtk6592). After upload  phone doesn't start
(on display logo fly and nothing again, this is best result. On any pack phone set cycle reboot).

Resend orig boot to phone, phone start normal.

link to orig boot:https://www.sendspace.com/file/t5zuy1
link to mod boot(after repack): https://www.sendspace.com/file/xicqss

**Comment by bgcngm** [comment]
Please use the official support thread (http://forum.xda-developers.com/showthread.php?t=1587411) for these kind of reports. If it is proven to be an error of the scripts (and not on your end), then you should open an issue on Github.
