### ISSUE TITLE
MT8127

### ISSUE THREAD

**Issue by ludvigaldrin** [bgcngm/mtk-tools#15]
Hi!
We have used your tool for many MTK devices with great success. However now we have Lenovo A7-10 that we want to use and this version uses the MT8127 chip. We use CWM 6.0.30 to extract the boot.img and your tool can extract it. Then we modify the default.props and repacka it. One noticeable thing here is that the size of the original boot.img is about 6.2 MB and after repack its around 4MB. But then when we reload it and set a md5 sum we get MD5 sum missmatch. If I work around this and force the new boot.img to load the device cant boot correct and has a lot of issues.

Do you know if there is anything special with MT8127 since you dont have it in your list? Can support for this version be added?

Thanks for a great tool anyhow

**Comment by bgcngm** [comment]
The list of supported devices is not updated very often, doesn't mean MT8127 is not supported.

The size of the original image can be different to the newly repacked image, because sometimes the images are full partition dumps (matching the size of the partition). That is probably what is happening to you. Also, each repack will have a different MD5 hash, that's perfectly normal.

As far as it concerns to the problems you're having, most likely it is on your side. Double check what you are changing between unpack and repack. And make sure the running environment is supported.

**Comment by ludvigaldrin** [comment]
Hmm okay. The thing is that if I do an export with CWM get the boot.img. Unpack and then directly do a repack without modifying anything. I then run md5 on the file and update the nandroid file with it I always get md5 missmatch. If I remove the nandroid file which then forces the restore without md5 it stucks in boot up loop. Which is super strange. We have successfully done this to around 500 units of Lenovo A7-40 and A7-50 but with A7-10 its not working at all.

But I guess by the sound of what your saying that there should not be any issue in your scripts then. I guess there could be something wrong with the CWM backup/restore as well.

Thanks anyhow for you great product

**Comment by bgcngm** [comment]
If you're doing a backup within CWM / TWRP recovery, you get the full boot and /or recovery partitions back'ed up. It is totally normal to have for example a boot image file with exactly 6MB, that turns to be only ~4MB after repacking. In this situation, MD5 checksum will be obviously different.

**Comment by ludvigaldrin** [comment]
Yes, but since I update the MD5 checksum in the nandroid file it should still work right?

**Comment by bgcngm** [comment]
Sure, you have to edit the file so that it matches the new MD5 sum. Unpacking and repacking without any changes to the image should be okay. Are you using Ubuntu for that?

**Comment by ludvigaldrin** [comment]
Using MAC terminal for it. Everything looks really good during the process. So between the times we have done this before and now the difference is that we use a different version of CWM and that its another MTK model. Otherwise we have done this a lot of times with great success. But now the boot.img wont restore :(

**Comment by ludvigaldrin** [comment]
Where do you live? We can send you a tablet for free. The only thing we want is to get rid of the ADB secure setting. So however you do that we will be really grateful.

**Comment by bgcngm** [comment]
Contact me via PM on XDA, please.
